path:
  ckpt_path: "./output/0624a/ckpt/Ego4D_final_v5"
  log_path: "./output/0624a/log/Ego4D_final_v5"
  result_path: "./output/0624a/result/Ego4D_final_v5"
  # ckpt_path: "/content/drive/MyDrive/sheffield_work/intermediate_files/0506a/output/ckpt/Ego4D_final_v5"
  # log_path: "/content/drive/MyDrive/sheffield_work/intermediate_files/0506a/output/log/Ego4D_final_v5"
  # result_path: "/content/drive/MyDrive/sheffield_work/intermediate_files/0506a/output/result/Ego4D_final_v5"
optimizer:
  batch_size: 24
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 900000
  log_step: 100
  synth_step: 1000
  val_step: 1000
  save_step: 100000
